version: '3.8'

services:
  db:
    image: postgres:13
    container_name: bravo-postgres
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_go_app
    env_file:
      - .env.local
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
